spring:
  application:
    name: employee-management-software

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/ems?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root

  liquibase:
    change-log: classpath:db/app-changelog.xml
